### ISSUE TITLE
Ordered mappings?

### ISSUE THREAD

**Issue by vpanteleev-sym** [dlang-community/configy#51]
Hi,

Is it possible to read a mapping but preserve the order? I.e. into something like https://ae.dpldocs.info/ae.utils.aa.OrderedMap.html ?

Thanks!

**Comment by Geod24** [comment]
You can always define a custom time and provide a `fromYAML`. I'm not sure what the use case is though ?

**Comment by vpanteleev-sym** [comment]
> You can always define a custom time and provide a `fromYAML`.

I have had trouble with that approach in the past as it was constantly causing temporal paradoxes. Could an UDA be used instead?

> I'm not sure what the use case is though ?

Consider e.g.:

```yaml
databases:
  development:
    matches: "development"
    expiry: never
  default:
    matches: "*"
    expiry: 2 weeks
```

We would like to preserve the order, as otherwise, the "default" entry may be ordered in front of the "development" entry, therefore always matching before it. A list could be used here to avoid this problem, but I think it's useful to also be able to have order-preserving mappings.
